from __future__ import annotations

import re
from typing import Any

from app.analyst.providers.base import (
    AIProvider,
)


class MockAnalystProvider(
    AIProvider,
):
    """
    Deterministic development provider.

    It does NOT use an LLM.

    It produces a realistic report shape so the rest
    of the product can be built and tested for free.
    """

    provider_name = "mock"

    model_name = (
        "deterministic-mock-analyst-v1"
    )

    def _evidence_ids(
        self,
        prompt: str,
    ) -> list[str]:
        values = re.findall(
            r'"evidence_id"\s*:\s*"(E\d+)"',
            prompt,
        )

        return list(
            dict.fromkeys(
                values
            )
        )

    def generate_json(
        self,
        prompt: str,
    ) -> dict[str, Any]:
        evidence_ids = (
            self._evidence_ids(
                prompt
            )
        )

        text = prompt.lower()

        suspicious = any(
            phrase in text
            for phrase in [
                "brand impersonation",
                "corroborated impersonation",
                "credential/account-related",
                '"is_suspicious": true',
            ]
        )

        if suspicious:
            verdict = (
                "likely_phishing"
            )

            confidence = 88.0

            summary = (
                "The supplied deterministic evidence "
                "contains multiple indicators consistent "
                "with credential phishing or brand "
                "impersonation."
            )

        else:
            verdict = (
                "insufficient_evidence"
            )

            confidence = 55.0

            summary = (
                "The supplied evidence does not provide "
                "enough malicious indicators for a "
                "high-confidence phishing determination."
            )

        findings = []

        if evidence_ids:
            findings.append(
                {
                    "title": (
                        "Deterministic evidence reviewed"
                    ),

                    "explanation": (
                        "The analyst assessment is based "
                        "only on the supplied evidence "
                        "package."
                    ),

                    "evidence_ids": [
                        evidence_ids[
                            0
                        ]
                    ],

                    "severity": (
                        "high"
                        if suspicious
                        else "info"
                    ),
                }
            )

        return {
            "investigation_id": (
                self._investigation_id(
                    prompt
                )
            ),

            "verdict": verdict,

            "confidence": (
                confidence
            ),

            "executive_summary": (
                summary
            ),

            "findings": (
                findings
            ),

            "recommended_actions": (
                [
                    "Do not enter credentials into the destination.",
                    "Review the originating email before interacting further.",
                ]
                if suspicious
                else [
                    "Continue monitoring.",
                    "Review additional evidence if available.",
                ]
            ),

            "mitre_attack": (
                [
                    {
                        "technique_id": (
                            "T1566"
                        ),

                        "technique_name": (
                            "Phishing"
                        ),

                        "reason": (
                            "The supplied evidence "
                            "contains phishing-related "
                            "impersonation indicators."
                        ),
                    }
                ]
                if suspicious
                else []
            ),

            "limitations": [
                (
                    "This report was generated by the "
                    "deterministic development provider "
                    "and not by a live language model."
                )
            ],
        }

    def _investigation_id(
        self,
        prompt: str,
    ) -> str:
        match = re.search(
            r'"investigation_id"\s*:\s*"([^"]+)"',
            prompt,
        )

        if match:
            return match.group(
                1
            )

        return "unknown-investigation"
